import { test, expect, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

async function open(page: Page) {
  await page.goto('/floorplanner/test-workspace')
  const cookie = page.getByRole('button', { name: 'Essential only' }), start = page.getByRole('button', { name: 'Start Editing' })
  await expect.poll(async () => await cookie.isVisible() || await start.isVisible() || await page.getByRole('button', { name: 'Project', exact: true }).isVisible()).toBe(true)
  if (await cookie.isVisible()) await cookie.click()
  await start.click()
  await page.getByRole('button', { name: 'Space', exact: true }).click()
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Import building drawing', exact: true }).click()
}

async function backup(page: Page) {
  await page.getByRole('button', { name: 'Project', exact: true }).click()
  const pending = page.waitForEvent('download')
  await page.getByRole('menuitem', { name: /Download backup/ }).click()
  return JSON.parse(await readFile((await (await pending).path())!, 'utf8')).data
}

test('recovers a review draft and saves rooms, checked scale, round pillars and exit openings', async ({ page }) => {
  await open(page)
  const base64 = await page.evaluate(() => {
    const c = document.createElement('canvas'); c.width = 800; c.height = 600
    const ctx = c.getContext('2d')!; ctx.fillStyle = 'white'; ctx.fillRect(0, 0, 800, 600)
    ctx.strokeStyle = '#111'; ctx.lineWidth = 6; ctx.strokeRect(20, 20, 750, 550)
    ctx.fillStyle = '#111'; ctx.fillRect(380, 270, 18, 18)
    return c.toDataURL('image/png').split(',')[1]
  })
  await page.getByLabel('Floor plan drawing files').setInputFiles({ name: 'recovery.png', mimeType: 'image/png', buffer: Buffer.from(base64, 'base64') })
  const dialog = page.getByRole('dialog', { name: 'Import & trace building' })
  await expect(dialog.getByText(/4 walls · 1 pillars/)).toBeVisible()
  const svg = dialog.getByLabel('Review building on recovery.png')
  const box = (await svg.boundingBox())!
  await svg.click({ position: { x: box.width * .125, y: box.height / 6 } })
  await svg.click({ position: { x: box.width * .625, y: box.height / 6 } })
  await dialog.getByLabel('Known distance for recovery.png').fill('40')
  await dialog.getByRole('button', { name: 'Apply scale', exact: true }).click()
  await dialog.getByRole('button', { name: 'Set scale', exact: true }).click()
  await svg.click({ position: { x: box.width * .125, y: box.height / 6 } })
  await svg.click({ position: { x: box.width * .125, y: box.height / 2 } })
  await dialog.getByLabel('Known distance for recovery.png').fill('20')
  await dialog.getByRole('button', { name: 'Verify second distance' }).click()
  await expect(dialog.getByText(/Scale check passed/)).toBeVisible()
  await dialog.getByRole('button', { name: 'Room boundary', exact: true }).click()
  await dialog.getByRole('button', { name: 'Build rooms from connected walls' }).click()
  await dialog.getByLabel('Room name').fill('Main hall')
  await dialog.getByRole('button', { name: 'Edit mark', exact: true }).click()
  await dialog.getByLabel('Selected building mark').selectOption({ index: 5 })
  await dialog.getByLabel('Pillar shape').selectOption('ellipse')
  await dialog.getByLabel('Selected building mark').selectOption({ index: 1 })
  await dialog.getByLabel('Opening type').selectOption('exit')
  await dialog.getByRole('button', { name: 'Cut opening', exact: true }).click()
  await expect(dialog.getByText(/5 walls · 1 pillars/)).toBeVisible()
  await dialog.getByRole('button', { name: 'Detect walls & pillars again' }).click()
  await expect(dialog.getByText(/5 walls · 1 pillars/)).toBeVisible()
  await expect(dialog.getByText('Review draft saved on this device.')).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Start Editing' }).click()
  await page.getByRole('button', { name: 'Space', exact: true }).click()
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Import building drawing', exact: true }).click()
  await page.getByRole('button', { name: 'Resume review' }).click()
  await expect(dialog.getByText(/Scale check passed/)).toBeVisible()
  await dialog.getByRole('checkbox', { name: 'I checked the walls, pillars, and scale.' }).check()
  await dialog.getByRole('button', { name: 'Import scaled building' }).click()
  const data = await backup(page), drawing = Object.values(data.backgroundImages)[0] as any
  expect(data.room.importedPolygons[0].label).toBe('Main hall')
  expect(drawing.plan.rooms[0].vertices).toHaveLength(4)
  expect(drawing.plan.openings[0].kind).toBe('exit')
  expect(drawing.plan.structures.find((s: any) => s.kind === 'pillar').shape).toBe('ellipse')
  expect(drawing.plan.verification.inches).toBe(240)
  expect(Object.keys(data.tables)).toHaveLength(0)
})

test('image import detects only structures, requires scale, and preserves editable geometry after reload', async ({ page }) => {
  await open(page)
  const base64 = await page.evaluate(() => {
    const c = document.createElement('canvas'); c.width = 800; c.height = 600
    const ctx = c.getContext('2d')!; ctx.fillStyle = 'white'; ctx.fillRect(0, 0, 800, 600)
    ctx.strokeStyle = '#111'; ctx.lineWidth = 6; ctx.strokeRect(20, 20, 750, 550)
    ctx.fillStyle = '#111'; ctx.fillRect(380, 270, 18, 18)
    ctx.lineWidth = 2; for (let i = 0; i < 6; i++) ctx.strokeRect(70 + i * 110, 150, 65, 27)
    return c.toDataURL('image/png').split(',')[1]
  })
  await page.getByLabel('Floor plan drawing files').setInputFiles({ name: 'venue.png', mimeType: 'image/png', buffer: Buffer.from(base64, 'base64') })
  const dialog = page.getByRole('dialog', { name: 'Import & trace building' })
  await expect(dialog.getByText(/4 walls · 1 pillars/)).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Import scaled building' })).toBeDisabled()
  const svg = dialog.getByLabel('Review building on venue.png')
  await svg.scrollIntoViewIfNeeded()
  const box = (await svg.boundingBox())!
  await svg.click({ position: { x: box.width * .125, y: box.height / 6 } })
  await svg.click({ position: { x: box.width * .625, y: box.height / 6 } })
  await dialog.getByLabel('Known distance for venue.png').fill('40')
  await dialog.getByRole('button', { name: 'Apply scale', exact: true }).click()
  await expect(dialog.getByText(/Page size: 80.0 × 60.0 ft/)).toBeVisible()
  await dialog.getByLabel('Drawing opacity').fill('0')
  await dialog.getByRole('checkbox', { name: 'I checked the walls, pillars, and scale.' }).check()
  await dialog.getByRole('button', { name: 'Import scaled building' }).click()
  const data = await backup(page)
  expect(Object.keys(data.tables)).toHaveLength(0)
  const drawing = Object.values(data.backgroundImages)[0] as any
  expect(drawing.plan.structures).toHaveLength(5)
  expect(drawing.width).toBeCloseTo(960, 0)
  expect(drawing.height).toBeCloseTo(720, 0)
  expect(drawing.plan.calibrated).toBe(true)
  await page.screenshot({ path: 'test-results/building-import-canvas.png' })
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Start Editing' }).click()
  await page.getByRole('button', { name: 'Space', exact: true }).click()
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Edit walls, pillars & scale' }).click()
  await expect(page.getByText(/4 walls · 1 pillars · Scale confirmed/)).toBeVisible()
  const review = page.getByRole('dialog', { name: 'Import & trace building' })
  await review.getByLabel('Selected building mark').selectOption({ index: 1 })
  const originalWidth = await review.getByLabel('Mark width').inputValue()
  await review.getByLabel('Mark width').fill('600')
  await review.getByLabel('Mark width').press('Tab')
  await expect(review.getByLabel('Mark width')).toHaveValue('600')
  await review.getByRole('button', { name: 'Undo review change' }).click()
  await expect(review.getByLabel('Mark width')).toHaveValue(originalWidth)
  await review.getByRole('button', { name: 'Redo review change' }).click()
  await expect(review.getByLabel('Mark width')).toHaveValue('600')
  await review.getByRole('button', { name: 'Delete selected mark' }).click()
  await expect(review.getByText(/3 walls · 1 pillars/)).toBeVisible()
  await review.getByRole('button', { name: 'Undo review change' }).click()
  await expect(review.getByText(/4 walls · 1 pillars/)).toBeVisible()
  await page.screenshot({ path: 'test-results/building-import-review.png' })
  await review.getByRole('checkbox', { name: 'I checked the walls, pillars, and scale.' }).check()
  await review.getByRole('button', { name: 'Save building changes' }).click()
  const corrected = Object.values((await backup(page)).backgroundImages)[0] as any
  expect(corrected.plan.structures[0].width * corrected.width / corrected.plan.sourceWidth).toBeCloseTo(600, 2)
})

test('restricting detection to the room excludes the sheet border and supports undo', async ({ page }) => {
  await open(page)
  const base64 = await page.evaluate(() => {
    const c = document.createElement('canvas'); c.width = 800; c.height = 600
    const ctx = c.getContext('2d')!; ctx.fillStyle = 'white'; ctx.fillRect(0, 0, 800, 600)
    ctx.strokeStyle = '#111'; ctx.lineWidth = 4; ctx.strokeRect(5, 5, 790, 590); ctx.strokeRect(100, 100, 600, 400)
    return c.toDataURL('image/png').split(',')[1]
  })
  await page.getByLabel('Floor plan drawing files').setInputFiles({ name: 'border.png', mimeType: 'image/png', buffer: Buffer.from(base64, 'base64') })
  const dialog = page.getByRole('dialog', { name: 'Import & trace building' })
  await expect(dialog.getByText(/8 walls/)).toBeVisible()
  await dialog.getByRole('button', { name: 'Detection area', exact: true }).click()
  const svg = dialog.getByLabel('Review building on border.png')
  await svg.scrollIntoViewIfNeeded()
  const box = (await svg.boundingBox())!
  // Keep the gesture in the visible viewport; select the upper half of the room.
  await page.mouse.move(box.x + box.width * .1, box.y + box.height * .1)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width * .9, box.y + box.height * .45, { steps: 5 })
  await page.mouse.up()
  await expect(dialog.getByRole('button', { name: 'Use whole page' })).toBeVisible()
  await dialog.getByRole('button', { name: 'Detect walls & pillars again' }).click()
  await expect(dialog.getByText(/3 walls/)).toBeVisible()
  await dialog.getByRole('button', { name: 'Undo review change' }).click()
  await expect(dialog.getByText(/8 walls/)).toBeVisible()
})

test('PDF dimension labels are selectable and every page needs its own scale', async ({ page }) => {
  await open(page)
  const { jsPDF } = await import('jspdf')
  const pdf = new jsPDF({ unit: 'pt', format: [600, 400], orientation: 'landscape' })
  pdf.setLineWidth(4); pdf.rect(30, 50, 500, 280); pdf.text(`40'-0"`, 180, 35)
  pdf.addPage([600, 400], 'landscape'); pdf.rect(30, 50, 500, 280); pdf.text('12 m', 180, 35)
  await page.getByLabel('Floor plan drawing files').setInputFiles({ name: 'halls.pdf', mimeType: 'application/pdf', buffer: Buffer.from(pdf.output('arraybuffer')) })
  const dialog = page.getByRole('dialog', { name: 'Import & trace building' })
  const label = dialog.getByLabel('Dimension label for halls.pdf - page 1')
  await expect(label).toBeVisible()
  await label.selectOption(`40'-0"`)
  await expect(dialog.getByLabel('Known distance for halls.pdf - page 1')).toHaveValue('480')
  await expect(dialog.getByLabel('Distance unit for halls.pdf - page 1')).toHaveValue('in')
  await dialog.getByRole('button', { name: /Page 2 halls/ }).click()
  await expect(dialog.getByLabel('Dimension label for halls.pdf - page 2')).toBeVisible()
  await dialog.getByRole('checkbox', { name: 'I checked the walls, pillars, and scale.' }).check()
  await expect(dialog.getByRole('button', { name: 'Import scaled building' })).toBeDisabled()
  await page.screenshot({ path: 'test-results/building-import-pdf.png' })
})

test('flat DXF preserves drawing units without creating furniture', async ({ page }) => {
  await open(page)
  const dxf = ['0','SECTION','2','HEADER','9','$INSUNITS','70','2','0','ENDSEC','0','SECTION','2','ENTITIES','0','LINE','8','A-WALL','10','0','20','0','11','40','21','0','0','LINE','8','A-WALL','10','0','20','0','11','0','21','20','0','CIRCLE','8','COLUMN','10','15','20','10','40','1','0','LINE','8','TABLES','10','5','20','5','11','8','21','5','0','ENDSEC','0','EOF'].join('\n')
  await page.getByLabel('Floor plan drawing files').setInputFiles({ name: 'building.dxf', mimeType: 'application/dxf', buffer: Buffer.from(dxf) })
  const dialog = page.getByRole('dialog', { name: 'Import & trace building' })
  await expect(dialog.getByText(/2 walls · 1 pillars · Scale confirmed/)).toBeVisible()
  await dialog.getByRole('checkbox', { name: 'I checked the walls, pillars, and scale.' }).check()
  await dialog.getByRole('button', { name: 'Import scaled building' }).click()
  const data = await backup(page), drawing = Object.values(data.backgroundImages)[0] as any
  expect(Object.keys(data.tables)).toHaveLength(0)
  expect(drawing.plan.structures).toHaveLength(3)
  expect(drawing.plan.structures[0].width * drawing.width / drawing.plan.sourceWidth).toBeCloseTo(480, 3)
})
