import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy Policy" };

export default function PrivacyPage() {
  return <main className="container-narrow py-10"><article className="rounded-3xl border border-slate-200 bg-white p-6 leading-7 text-slate-700 sm:p-10">
    <h1 className="text-3xl font-semibold text-slate-950">Privacy Policy</h1><p className="mt-2 text-sm">Effective August 30, 2026.</p>
    <h2 className="mt-8 text-xl font-semibold text-slate-950">Information we collect</h2><p className="mt-2">We collect account details, alert preferences, show submissions, promoter information, floor-plan content, security logs, and technical information needed to operate Card Show Nation.</p>
    <h2 className="mt-8 text-xl font-semibold text-slate-950">How we use information</h2><p className="mt-2">We use information to provide accounts, publish shows, deliver requested alerts, secure the service, prevent abuse, provide support, and improve the product. Optional analytics and advertising are disabled unless you accept them.</p>
    <h2 className="mt-8 text-xl font-semibold text-slate-950">Public promoter contact</h2><p className="mt-2">Account emails and submitter emails are private. We only show a promoter email publicly when a promoter or submitter enters a separate public promoter email and confirms that it may be published for visitor contact. Existing organizer emails are not treated as public consent by default.</p>
    <h2 className="mt-8 text-xl font-semibold text-slate-950">Location fallback</h2><p className="mt-2">If you use the nearby-shows feature and your browser location is unavailable, we may use an IP-based fallback. That fallback sends the visitor IP address to ip-api.com so the service can estimate a general location.</p>
    <h2 className="mt-8 text-xl font-semibold text-slate-950">Sharing and retention</h2><p className="mt-2">We use providers for hosting, databases, storage, email, analytics, advertising, payment processing, flyer storage, and abuse prevention. We do not sell account contact information. Public show details, venue information, links, and consented public promoter contact details are visible to visitors.</p><p className="mt-2">We keep account records while the account is active, show listings while they are useful for the directory or business records, security logs for abuse prevention, and transaction records as needed for tax, legal, and payment-dispute purposes. When data is deleted from active systems, backup copies age out on the backup provider&apos;s normal rotation schedule; we do not restore deleted personal information from backups except for security, legal, or disaster-recovery needs.</p>
    <h2 className="mt-8 text-xl font-semibold text-slate-950">Your choices</h2><p className="mt-2">You can change alerts, unsubscribe, choose essential-only cookies, or delete your account. Contact privacy@cardshownation.com for access or correction requests.</p>
  </article></main>;
}
